# Generated by Django 3.1.1 on 2020-10-01 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_roastboast_total_votes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roastboast',
            name='content',
            field=models.CharField(blank=True, max_length=280),
        ),
        migrations.AlterField(
            model_name='roastboast',
            name='post_type',
            field=models.CharField(blank=True, choices=[('Boast', 'Boast'), ('Roast', 'Roast')], max_length=6),
        ),
    ]
